/**
 * @(#)Pyth.java
 * @CS 110 Sample Program 
 * @8-20-08
 * @Demonstrates interactive input
 * @Calculates Pythagorean Triples
 */


import java.util.Scanner;

public class Pyth 
{
	public static void main (String[] args) 
	{
		int side1, side2, side3;
		int seed1, seed2;
		
		Scanner sc1	=	new Scanner(System.in);
		
		//Welcome message
		System.out.println
		    ("Welcome to Generating Pythagorean Triples");
		System.out.println
		    ("This program requires two seed values, to ");
		System.out.println("generate the triples");		
		
		//Input the seed values
		System.out.println();
		System.out.println
		    ("Enter the smaller of the seed values ");
		seed1		=	sc1.nextInt();
		System.out.println();
		System.out.println
		    ("Enter the large of the seed values ");
		seed2 = sc1.nextInt();	
		
		//Generate the triple
		side1	=	seed2 * seed2 - seed1 * seed1;
		side2	=	2 * seed1 * seed2;
		side3	=	seed2 * seed2 + seed1 * seed1;
		
		//Output the results
		System.out.println();
		System.out.println("The triple generated by " 
		      + seed1 + ", " + seed2 + " is ");
		System.out.println
		    (side1 + ", " + side2 + ", " + side3);		
    }  
    
}